# Generated by Django 4.2.13 on 2025-02-10 19:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("translations", "0006_alter_language_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload the image of the post.",
                        null=True,
                        upload_to="posts/",
                    ),
                ),
                ("published_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Enter the code to be used in the codebase",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the category", max_length=255
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "language",
                    models.ForeignKey(
                        help_text="Choose the language of this variation of the selected post.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="translations.language",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="Choose the main post this variation belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landing_page.post",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                help_text="Choose the category of the post.",
                on_delete=django.db.models.deletion.RESTRICT,
                to="landing_page.postcategory",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.ForeignKey(
                help_text="Choose the slug of the post title.",
                on_delete=django.db.models.deletion.RESTRICT,
                to="translations.slug",
            ),
        ),
    ]
