# Generated by Django 4.2.13 on 2025-02-10 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0006_alter_language_status"),
        ("landing_page", "0003_alter_postcategory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcategory",
            name="internal_name",
            field=models.CharField(
                default="",
                help_text="Enter the name of the category, for use in this admin area.",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="postcategory",
            name="name",
            field=models.ForeignKey(
                help_text="Select the slug of the post category",
                on_delete=django.db.models.deletion.CASCADE,
                to="translations.slug",
            ),
        ),
    ]
