# Generated by Django 4.2.13 on 2025-02-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_page", "0004_postcategory_internal_name_alter_postcategory_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="internal_name",
            field=models.CharField(
                default="",
                help_text="Enter the name of the post, for use in this admin area.",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
