# Generated by Django 4.2.13 on 2025-02-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUsMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("message", models.TextField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PE", "Pending"),
                            ("PR", "Processing"),
                            ("RE", "Rejected"),
                            ("CO", "Completed"),
                        ],
                        default="PE",
                        max_length=2,
                    ),
                ),
                ("date_submitted", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
