# Generated by Django 4.2.13 on 2025-03-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_messages", "0002_volunteersector_volunteerapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteersector",
            name="is_other",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="volunteersector",
            name="code",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
