# Generated by Django 4.2.13 on 2025-02-18 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("team_members", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobrole",
            name="code",
        ),
        migrations.AlterField(
            model_name="member",
            name="job_role",
            field=models.ForeignKey(
                help_text="Select the job role of the team member.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="team_members.jobrole",
            ),
        ),
    ]
