# Generated by Django 4.2.13 on 2025-02-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_members", "0003_alter_member_job_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="profile_image",
            field=models.ImageField(
                help_text="Upload the profile image of the team member.",
                null=True,
                upload_to="images/team_members/",
            ),
        ),
    ]
