# Generated by Django 4.2.13 on 2025-03-01 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0006_alter_language_status"),
        ("team_members", "0004_alter_member_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="description",
            field=models.ForeignKey(
                help_text="Select the slug of team member description.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="translations.slug",
            ),
        ),
    ]
