# Generated by Django 4.2.13 on 2025-03-18 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("team_members", "0006_membercategory_member_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membercategory",
            options={"verbose_name_plural": "Member Categories"},
        ),
    ]
