# Generated by Django 4.2.13 on 2025-02-20 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("translations", "0006_alter_language_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload the image of the program.",
                        null=True,
                        upload_to="programs/images/",
                    ),
                ),
                (
                    "description",
                    models.ForeignKey(
                        help_text="Select the description of the Program",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_description_slug",
                        to="translations.slug",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        help_text="Select the slug of the Program",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_name_slug",
                        to="translations.slug",
                    ),
                ),
            ],
        ),
    ]
