# Generated by Django 4.2.13 on 2025-02-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0002_program_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="image",
            field=models.ImageField(
                help_text="Upload the image of the program.",
                null=True,
                upload_to="images/programs/",
            ),
        ),
    ]
