# Generated by Django 4.2.13 on 2025-03-01 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0007_alter_language_code_alter_language_name_and_more"),
        ("programs", "0003_alter_program_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="description",
            field=models.ForeignKey(
                help_text="Select the slug of the program description.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="program_description_slug",
                to="translations.slug",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="name",
            field=models.ForeignKey(
                help_text="Select the slug of the program name.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="program_name_slug",
                to="translations.slug",
            ),
        ),
    ]
