# Generated by Django 4.2.13 on 2025-03-18 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0007_alter_language_code_alter_language_name_and_more"),
        ("programs", "0004_alter_program_description_alter_program_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                (
                    "name",
                    models.ForeignKey(
                        help_text="Select the slug of the program category.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="translations.slug",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="program",
            name="category",
            field=models.ForeignKey(
                default="",
                help_text="Select the program category.",
                on_delete=django.db.models.deletion.CASCADE,
                to="programs.programcategory",
            ),
            preserve_default=False,
        ),
    ]
