# Generated by Django 4.2.13 on 2025-03-18 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0005_programcategory_program_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programcategory",
            options={"verbose_name_plural": "Program Categories"},
        ),
    ]
