# Generated by Django 4.2.13 on 2025-02-12 20:00

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("news_and_events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postvariation",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Content"),
        ),
    ]
