# Generated by Django 4.2.13 on 2025-02-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_and_events", "0002_alter_postvariation_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload the image of the post.",
                null=True,
                upload_to="images/posts/",
            ),
        ),
    ]
