# Generated by Django 4.2.13 on 2025-02-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_and_events", "0003_alter_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="internal_name",
        ),
        migrations.RemoveField(
            model_name="postcategory",
            name="internal_name",
        ),
    ]
