# Generated by Django 4.2.13 on 2025-02-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_and_events", "0004_remove_post_internal_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_date",
            field=models.DateField(),
        ),
    ]
