# Generated by Django 4.2.13 on 2025-03-01 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0007_alter_language_code_alter_language_name_and_more"),
        ("news_and_events", "0005_alter_post_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcategory",
            name="code",
            field=models.CharField(
                help_text="Enter the code to be used in the codebase.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="postcategory",
            name="name",
            field=models.ForeignKey(
                help_text="Select the slug of the post category name.",
                on_delete=django.db.models.deletion.CASCADE,
                to="translations.slug",
            ),
        ),
    ]
