# Generated by Django 4.2.13 on 2025-02-08 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Please enter a 2-digit ISO 639-1 language code.",
                        max_length=2,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Please enter the name of the ISO 639-1 language code.",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Please enter the text of this translation",
                        max_length=255,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        help_text="Please select the language of this translation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="translations.language",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Slug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Please enter a code identifying the slug.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Please enter a description of the slug.",
                        max_length=255,
                    ),
                ),
                (
                    "translations",
                    models.ManyToManyField(
                        help_text="Please select a translation for the slug.",
                        related_name="slug_translations",
                        to="translations.language",
                    ),
                ),
            ],
        ),
    ]
