# Generated by Django 4.2.13 on 2025-02-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slug",
            name="translations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Please select a translation for the slug.",
                related_name="slug_translations",
                to="translations.translation",
            ),
        ),
    ]
