# Generated by Django 4.2.13 on 2025-02-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0002_alter_slug_translations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slug",
            name="translations",
        ),
        migrations.AddField(
            model_name="translation",
            name="slug",
            field=models.ForeignKey(
                default="",
                help_text="Please select the slug identifying the translation.",
                on_delete=django.db.models.deletion.CASCADE,
                to="translations.slug",
            ),
            preserve_default=False,
        ),
    ]
