# Generated by Django 4.2.13 on 2025-02-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0003_remove_slug_translations_translation_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
