# Generated by Django 4.2.13 on 2025-02-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0004_language_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
