# Generated by Django 4.2.13 on 2025-03-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0007_alter_language_code_alter_language_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slug",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Enter a code identifying the slug.",
                max_length=255,
                unique=True,
            ),
        ),
    ]
