# Generated by Django 4.2.13 on 2025-02-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("social_category", "Social Category"),
                            ("contact_category", "Contact Category"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("location", "Location"),
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
            ],
        ),
    ]
